version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@3.1.5
  # Exercise: Config and Deployment
jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fe:5e:d0:0b:ab:60:16:68:a8:89:91:b1:f7:25:da:03"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml

workflows: 
  configure-infra-workflow: 
    jobs: 
      - configure_infrastructure
